name: variables and secrets

env:
  WF_VAR: "WorkFlow level variable"

on:
  push:

jobs:
  test_variables:
    env:
        job_var: "Job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP:VAR: "Step level varaible"
        run: 
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo
          $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
